#!/bin/sh

if test `uname -s` = Darwin; then
    (cd commoncrypto && cargo $*)
fi
(cd fastpbkdf2 && cargo $*)
(cd octavo && cargo $*)
(cd openssl && cargo $*)
(cd ring && cargo $*)
(cd rust_crypto && cargo $*)
(cd sodiumoxide && cargo $*)
