#!/bin/sh

(cd fastpbkdf2 && cargo $*)
(cd octavo && cargo $*)
(cd openssl && cargo $*)
(cd ring && cargo $*)
(cd rust_crypto && cargo $*)
(cd RustCrypto && cargo + nightly $*)
(cd sodiumoxide && cargo $*)
