#!/bin/sh

(cd fastpbkdf2 && cargo +nightly $*)
(cd octavo && cargo +nightly $*)
(cd openssl && cargo +nightly $*)
(cd ring && cargo +nightly $*)
(cd rust_crypto && +nightly cargo $*)
(cd sodiumoxide && +nightly cargo $*)
